print("Masukkan nama Anda : ")
namaDepan = input()
print("Masukkan umur Anda : ")
umur = input()
alamat = input("Masukkan alamat Anda : ")
nim = input("Masukkan NIM Anda : ")

print("Nama saya adalah " + namaDepan)
print("Umut saya adalah " + umur)
print("Anda beralamat di " + alamat)
print("NIM anda adalah " + nim)