a = input("Masukkan nilai A = ")
b = input("Masukkan nilai B = ")
print("A == B = " + str(a==b))
print("A != B = " + str(a!=b))
print("A > B = " + str(a>b))
print("A < B = " + str(a<b))
print("A >= B = " + str(a>=b))
print("A <= B = " + str(a<=b))
print("A < 5 and B > 4 = " + str(int(a) < 5 and int(b) > 4))
print("A < 5 or B > 4 = " + str(int(a) < 5 or int(b) > 4))
print("not(A < 5 and B > 4) = " + str(not(int(a) < 5 and int(b) > 4)))